<head>
<title>Opentherm Gateway</title>
	<meta charset="utf-8">
	
	<meta name="application-name" content="Opentherm Gateway">
	<meta name="description" content="Opentherm Gateway">
	<meta name="author" content="Timoline">
	
	<!-- Mobile settings -->
	<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />
	
<!--<link rel="stylesheet" type="text/css" href="$theme.css">-->
	<!-- css -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="style.css" >
	<!-- js -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.js"></script>
	<script type='text/javascript' src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>