<title>Opentherm Gateway</title>
<meta charset="utf-8">

<meta name="application-name" content="Opentherm Gateway">
<meta name="description" content="Opentherm Gateway">
<meta name="author" content="Timoline">

<!-- Mobile settings -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--<link rel="stylesheet" type="text/css" href="$theme.css">-->
<!-- css -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="style.css" >
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">

<!-- js -->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>		
<script type="text/javascript" src="script.js"></script>		